In [1]:
import numpy as np

### Aggregate functions

In [ ]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print("Sum of the elements of array:",np.sum(array))
print("Average of the elements of array:",np.mean(array))
print("Minimum value in array:",np.min(array))
print("Maximum value in array:",np.max(array))
print("Position of minimum value :",np.argmin(array))
print("Position of maximum value :",np.argmax(array))

Sum of the elements of array: 55
Average of the elements of array: 5.5
Minimum value in array: 1
Maximum value in array: 10
Position of minimum value : 0
Position of maximum value : 9


In [8]:
# col sum
print(np.sum(array, axis = 0))

# row sum 
print(np.sum(array, axis = 1))

[ 7  9 11 13 15]
[15 40]


### Filtering

In [16]:
# Filtering refers to the process of selecting elements from an array that match a given condition

ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages<18]
print(teenagers)

adults = ages[(ages >= 18) & (ages<65)]
print(adults)

senior = ages[ages>=65]
print(senior)

even = ages[ages%2 == 0]
odd = ages[ages%2 != 0]

print(even)
print(odd)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
# where is used to preserve the original shape of data
adults = np.where(ages>=18 , ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


### Random Numbers

In [23]:
rng = np.random.default_rng(seed = 1)
# seeding is useful when we want to use the same set of data we have once genrated randomly


print(rng.integers(low=1,high=101,size=(2,3)))

[[48 52 76]
 [96  4 15]]


In [ ]:
# floating point number

print(np.random.uniform(low = -1,high = 1,size = (3,2)))

[[ 0.46638477 -0.0528733 ]
 [ 0.89976658  0.66712278]
 [-0.04482809  0.154803  ]]


In [38]:
array1 = np.array([1,2,3,4,5])
rng1 = np.random.default_rng()
rng.shuffle(array1)
print(array1)

fruits = np.array(["Apple","Orange","Mango","Banana","Pineapple"])
fruit = rng.choice(fruits,size = (3,2))
print(fruit)

[1 2 5 4 3]
[['Apple' 'Banana']
 ['Mango' 'Pineapple']
 ['Mango' 'Orange']]
