## NumPy array and basics

Learn about numpy

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array :",arr_1d)

1D array : [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array :",arr_2d)

2D array : [[1 2 3]
 [4 5 6]]


### List vs NumPy array

In [4]:
py_list = [1,2,3]
print("Python list multiplication", py_list*2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [5]:
arr = np.array([1,2,3])
print("Python array multiplication",arr*2)

Python array multiplication [2 4 6]


In [6]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List Operation time:", time.time()-start)

start = time.time()
np_arr = np.arange(1000000)*2
print("NumPy Operation time:",time.time()-start)

List Operation time: 0.06748127937316895
NumPy Operation time: 0.005697965621948242


### Creating array from scratch


In [7]:
zero_arr = np.zeros((3,4))
print("zeros array : \n",zero_arr)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones_arr = np.ones((2,3))
print("Ones array: \n", ones_arr)

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
full_arr = np.full((2,2),7)
print("Full array:\n",full_arr)

Full array:
 [[7 7]
 [7 7]]


In [10]:
random_arr = np.random.random((2,3))
print("Random array: \n ",random_arr)

Random array: 
  [[0.88639495 0.62167729 0.95941154]
 [0.42614474 0.85986806 0.86722955]]


In [11]:
sequence_arr = np.arange(0,11,2)
print("Sequence array:\n",sequence_arr)

Sequence array:
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [12]:
vector = np.array([1,2,3])
print("Vector:",vector)

Vector: [1 2 3]


In [13]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:",matrix)

Matrix: [[1 2 3]
 [4 5 6]]


In [14]:
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:",tensor)

Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [15]:
arr = np.array([[1,2,3],
               [4,5,6]])

print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("DType:",arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
DType: int64


### Array reshaping

In [16]:
arr = np.arange(12)
print("Original array :",arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array :",reshaped)

flattened = reshaped.flatten()
print("\nFlattened array :",flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled array :",raveled)

# Transpose
transpose = reshaped.T
print("\nTranspose array :",transpose)

Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
