In [1]:
import numpy as np

### Array and indexing

In [6]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
# chain indexing
print(array[0][0])
# multidimensional indexing is faster than chain indexing
print(array[0,0])

2
(2, 3)
1
1


### Slicing

In [14]:
array1 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:step]
# row
print(array1[0:3])
print(array1[::2]) # or array1[0:4:2]

# coloumn
print(array1[:, 0:4:2])

# row and col
print(array1[0:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[3 4]
 [7 8]]


### Arthimetic

In [16]:
# Scalar arthimetic
array2 = np.array([1,2,3])

print(array2 + 1)
print(array2 - 1)
print(array2 * 3)
print(array2 / 4)
print(array2 ** 5)

[2 3 4]
[0 1 2]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [22]:
# vectorized math functions

print(np.sqrt(array2))
array3 = np.array([1.01,2.56,3.99])
print(np.round(array3))
print(np.pi)

[1.         1.41421356 1.73205081]
[1. 3. 4.]
3.141592653589793


In [24]:
# Area of circle of a array of radius of circles
radii = np.array([1,2,3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [26]:
# Element wise arthimetic

array5 = np.array([1,2,3])
array6 = np.array([4,5,6])

print(array5 + array6)
print(array5 - array6)
print(array5 * array6)
print(array5 / array6)
print(array5 ** array6)




[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [32]:
# comparision operators

scores = np.array([91,55,100,73,82,64])
# gives boolean values
print(scores >= 60)
print(scores == 100)
print(scores < 60)

scores[scores<60] = 0
print(scores)

[ True False  True  True  True  True]
[False False  True False False False]
[False  True False False False False]
[ 91   0 100  73  82  64]


### Broadcasting


In [35]:
'''
Broadcasting allows NumPy to perform operations on arrays
with different shapes by virtually expanding dimensions 
so they match the larger array's shape

The dimensons have the same size 
OR
One of the dimensions has a size of 1
'''
 
array7 = np.array([[1,2,3,4]])
array8 = np.array([[1],[2],[3],[4]])

print(array7.shape)
print(array8.shape)

print(array7 * array8)


(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [37]:
array9 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array10 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array9.shape)
print(array10.shape)
print(array9 * array10)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
