## Numpy Array operations

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing :",arr[2:7])
print("With step :",arr[1:8:2])
print("Negative Indexing :",arr[-3])

Basic slicing : [3 4 5 6 7]
With step : [2 4 6 8]
Negative Indexing : 8


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element :",arr_2d[1,2])
print("Entire row :",arr_2d[1])
print("Entire coloumn :",arr_2d[:,1])


Specific element : 6
Entire row : [4 5 6]
Entire coloumn : [2 5 8]


## Sorting

In [10]:
unsorted_arr = np.array([3,1,4,1,5,9,6,2])
print("Sorted array :",np.sort(unsorted_arr))

unsorted_arr_2d = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array :",np.sort(unsorted_arr_2d, axis = 0))

Sorted array : [1 1 2 3 4 5 6 9]
Sorted 2D array : [[1 1]
 [2 2]
 [3 3]]


## Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print("Even numbers :",even_number)


Even numbers : [ 2  4  6  8 10]


### Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [14]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where() :",numbers[where_result])

[1 3 5]
NP where() : [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5,numbers*2 , numbers)
# where can have only condition or codition + operation if condition fullfill on the position of the array  
print("Condition array :" ,condition_array)
# more clear to understand working of where 
condition_array_1 = np.where(numbers<5,"True","False")
print("Condition based result :",condition_array_1)
# prints true for all the value less than 5 and false for others

Condition array : [ 1  2  3  4  5 12 14 16 18 20]
Condition based result : ['True' 'True' 'True' 'True' 'False' 'False' 'False' 'False' 'False'
 'False']


### Adding and Removing data

In [20]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6 7 8]


### Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
# Checking the shape we can say no of row and no of coloumn which decides what the shape is
print("Compatibility shapes:",a.shape == b.shape)

Compatibility shapes: False


In [26]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print("Original Array :\n",original)
print("Array with new row :\n",with_new_row)

new_col = np.array([[7],[8]])

with_new_col = np.hstack((original,new_col))
print("Original Array :\n",original)
print("Array with new coloumn :\n",with_new_col)

Original Array :
 [[1 2]
 [3 4]]
Array with new row :
 [[1 2]
 [3 4]
 [5 6]]
Original Array :
 [[1 2]
 [3 4]]
Array with new coloumn :
 [[1 2 7]
 [3 4 8]]


In [30]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print("Array after deletion :",deleted)

Array after deletion : [1 2 4 5 6]
