### Banking Transactions

A bank stores transaction amounts for 50 accounts across 20 days in a NumPy array.
Task:
- Separate debit and credit transactions
- Compute daily net balance changes
- Identify accounts with continuous negative balance trends

In [ ]:
import numpy as np

In [3]:
rng = np.random.default_rng(seed = 2)
data = rng.integers(-10000,10000,size=(50,20))
data

array([[ 6751, -4768, -7814, -4031, -1724,  6284,  -975, -8162, -3303,
         2002,  6263,  4571,  9857, -6242,  7604, -8898,  1164, -4501,
        -5973,  3148],
       [-3886,  1245, -4797, -6999,  4983, -1348,  3574,  3385,  8904,
        -1545, -5606,  2663,  8699,  9348,  7357,  3661, -2397, -2168,
        -9205, -6255],
       [-3341, -3081,  1594,   221,  3849,  7824,  7540,  5511,  9532,
        -3638,  8148,  8484, -5525,  -582,  1388,  3875,  4006, -7856,
         -462, -7910],
       [ 9156, -5962, -1019,  7688,   445,  3596,   -15,  6984,  1879,
         2888,  -923, -1870,  1872,   331,  5696,  1868,  -567,  7242,
        -5739, -1237],
       [ -277,  7844, -1193,  2274, -8470,  6587, -1113,   -39, -8065,
         3850,  2658, -3220,  5383,   456, -8863, -5676, -4825, -7986,
           21, -9228],
       [  442,  4038,  1585,  -872, -4648,  7954, -3564,  6703, -1124,
        -2299,  3868,  9473,  5711,  1841, -7865,  5317,  5712, -1857,
        -2742, -6077],
       [ 9

### Debit Transaction

In [4]:
debit = data[data<0]
debit

array([-4768, -7814, -4031, -1724,  -975, -8162, -3303, -6242, -8898,
       -4501, -5973, -3886, -4797, -6999, -1348, -1545, -5606, -2397,
       -2168, -9205, -6255, -3341, -3081, -3638, -5525,  -582, -7856,
        -462, -7910, -5962, -1019,   -15,  -923, -1870,  -567, -5739,
       -1237,  -277, -1193, -8470, -1113,   -39, -8065, -3220, -8863,
       -5676, -4825, -7986, -9228,  -872, -4648, -3564, -1124, -2299,
       -7865, -1857, -2742, -6077, -6565,  -127, -6376, -6836, -7748,
       -8089, -9602, -2411, -8012, -4437,  -989,  -231, -1086, -8901,
       -6161, -5468, -7808, -8071, -9160, -4078,  -353, -4945, -8302,
       -9744, -9320, -4068,  -383, -9804, -7793, -8851, -2804, -1083,
       -4924, -3633, -5209, -9020, -2209, -2680, -9865, -7041, -5803,
       -1190, -3954, -4842, -9934, -4292,  -688, -4213, -8812, -5819,
       -8720, -6304, -8267,  -866, -7792, -5114, -4995, -8946, -8278,
       -7833, -4902, -8588, -9184, -2288, -1068,  -611, -1880, -2411,
       -9099, -9121,

### Credit Transaction

In [5]:
credit = data[data>0]
credit

array([6751, 6284, 2002, 6263, 4571, 9857, 7604, 1164, 3148, 1245, 4983,
       3574, 3385, 8904, 2663, 8699, 9348, 7357, 3661, 1594,  221, 3849,
       7824, 7540, 5511, 9532, 8148, 8484, 1388, 3875, 4006, 9156, 7688,
        445, 3596, 6984, 1879, 2888, 1872,  331, 5696, 1868, 7242, 7844,
       2274, 6587, 3850, 2658, 5383,  456,   21,  442, 4038, 1585, 7954,
       6703, 3868, 9473, 5711, 1841, 5317, 5712, 9619, 5730, 2076, 7130,
       6659,  766, 2371, 2405, 2504,   80, 8746, 6400, 5007, 1489, 7624,
       2345,  131,  989, 9295,  974, 3780, 9690, 1101, 5630, 8543, 5691,
       2238, 6549,  113, 6473,  201, 9637, 4785, 9991, 5650,  469, 2521,
       7369, 9209, 5317, 5431, 2266, 3492, 8192, 9237, 3631, 9478, 1260,
       9230, 5413, 3795, 6786, 3373, 9608, 8066, 8543, 7339, 5875, 5401,
       9532, 6235, 2292, 9172, 2415,  236, 1932, 6091, 7747, 6480, 5060,
        935, 1858, 5849, 6571, 9489, 2103, 9353, 6174, 7653, 2674, 1187,
       4272, 2536,  973, 1168,  179, 1693, 8136, 64

### Daily net balance changes

In [6]:
net_balance = np.diff(data,axis = 1)
net_balance

array([[-11519,  -3046,   3783,   2307,   8008,  -7259,  -7187,   4859,
          5305,   4261,  -1692,   5286, -16099,  13846, -16502,  10062,
         -5665,  -1472,   9121],
       [  5131,  -6042,  -2202,  11982,  -6331,   4922,   -189,   5519,
        -10449,  -4061,   8269,   6036,    649,  -1991,  -3696,  -6058,
           229,  -7037,   2950],
       [   260,   4675,  -1373,   3628,   3975,   -284,  -2029,   4021,
        -13170,  11786,    336, -14009,   4943,   1970,   2487,    131,
        -11862,   7394,  -7448],
       [-15118,   4943,   8707,  -7243,   3151,  -3611,   6999,  -5105,
          1009,  -3811,   -947,   3742,  -1541,   5365,  -3828,  -2435,
          7809, -12981,   4502],
       [  8121,  -9037,   3467, -10744,  15057,  -7700,   1074,  -8026,
         11915,  -1192,  -5878,   8603,  -4927,  -9319,   3187,    851,
         -3161,   8007,  -9249],
       [  3596,  -2453,  -2457,  -3776,  12602, -11518,  10267,  -7827,
         -1175,   6167,   5605,  -3762,  -3

### Accounts with continious Negative balance trends

In [9]:
negative_trend = np.all(net_balance,axis = 1)
account_indices = np.where(negative_trend)[0]
account_indices

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])