### Online Learning Platform
An online platform tracks time spent (in minutes) by students on 6 courses over 14 days using a NumPy array.
Task:
- Compute total time spent per course
- Identify courses where average daily engagement exceeds a threshold
- Rank courses based on engagement


In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed = 42)
course_time_data = rng.integers(0,121,(6,14))
print("Time spent on courses over 14 days:\n",course_time_data)

Time spent on courses over 14 days:
 [[ 10  93  79  53  52 103  10  84  24  11  63 118  89  92]
 [ 86  95  62  15 101  54  60  44  22 112  94  77  48  99]
 [ 65  53  54  27  11  67 107   7 103 100  33  76  19  91]
 [ 84  42   8 117  53 108  82  94  91  23  44  56  60   5]
 [ 66  18  89  82 111  90  44 117  49  39 109  44   9  56]
 [ 96  22  56  15  83  57  39  27  68  81 113  52  19 100]]


In [4]:
time_per_course = course_time_data.sum(axis=1)
print("Total time spent per course :",time_per_course)

Total time spent per course : [881 969 813 867 923 828]


In [9]:
avg_daily_engagement = np.sum(course_time_data,axis=1)
# let's take mean as threshold
threshold = avg_daily_engagement.mean()
mask = avg_daily_engagement>threshold
print("Courses average engagement where they exceeds a threshold:",avg_daily_engagement[mask])

Courses average engagement where they exceeds a threshold: [881 969 923]


In [13]:
courses_ranking = time_per_course.argsort()[::-1]
print("Ranking of courses from 0 to 5:",courses_ranking)

Ranking of courses from 0 to 5: [1 4 0 3 5 2]
