### Retail Analytics

A retail company records daily sales of 5 products across 30 days in a 2D NumPy array of shape (30, 5).
Due to a system error, negative values appear in the dataset.
Task:
Replace negative values with 0
Compute the average weekly sales per product (assume 7 days = 1 week)
Identify the product with the highest average weekly sales


In [12]:
import numpy as np

In [13]:
rng = np.random.default_rng(seed = 10)
data = rng.integers(low = -10,high = 1000,size = (30,5))
print(data)

[[774 955 256 199 790]
 [826 509 140 831 507]
 [144 127 405 685 397]
 [840  -2 419 519 956]
 [227 823  62 331 746]
 [571 938 750 913 825]
 [127 932 843 136 978]
 [743 307 130 382 905]
 [783 218 486 851 637]
 [299 104 969 226 513]
 [689 315 511 275 835]
 [601 168 327 684 675]
 [305 145 139 242 787]
 [868 336 596 494 254]
 [525 140 481 128 237]
 [241  12 376 717 645]
 [774 835  51 773 105]
 [332  78 140 476 451]
 [351 432 415 569 619]
 [367 753 630 481 105]
 [831 225 324 764 854]
 [986 820 806 736 841]
 [555 793 236 451 791]
 [736 414 574 361 445]
 [ 26 263 740 863 803]
 [ 59 149 814 650 880]
 [456 417 235 831 147]
 [334  59 514 601 544]
 [540 184 371 326 682]
 [270 622 452 962 671]]


In [17]:
# Changes negative values to 0
data[data<0] = 0 
print(data)


[[774 955 256 199 790]
 [826 509 140 831 507]
 [144 127 405 685 397]
 [840   0 419 519 956]
 [227 823  62 331 746]
 [571 938 750 913 825]
 [127 932 843 136 978]
 [743 307 130 382 905]
 [783 218 486 851 637]
 [299 104 969 226 513]
 [689 315 511 275 835]
 [601 168 327 684 675]
 [305 145 139 242 787]
 [868 336 596 494 254]
 [525 140 481 128 237]
 [241  12 376 717 645]
 [774 835  51 773 105]
 [332  78 140 476 451]
 [351 432 415 569 619]
 [367 753 630 481 105]
 [831 225 324 764 854]
 [986 820 806 736 841]
 [555 793 236 451 791]
 [736 414 574 361 445]
 [ 26 263 740 863 803]
 [ 59 149 814 650 880]
 [456 417 235 831 147]
 [334  59 514 601 544]
 [540 184 371 326 682]
 [270 622 452 962 671]]


In [15]:
weekly_data = data[:28].reshape(4,7,5)
weekly_avg = weekly_data.mean(axis = 1)
print("Average weekly sales per product are:\n",weekly_avg)

Average weekly sales per product are:
 [[501.28571429 612.         410.71428571 516.28571429 742.71428571]
 [612.57142857 227.57142857 451.14285714 450.57142857 658.        ]
 [488.71428571 353.57142857 345.28571429 558.28571429 430.85714286]
 [450.28571429 416.42857143 559.85714286 641.85714286 635.85714286]]


In [16]:
avg = weekly_avg.mean(axis = 0)
print(avg)
max_idx = np.argmax(avg)
print("Product with the highest average weekly sales is on index:",max_idx)

[513.21428571 402.39285714 441.75       541.75       616.85714286]
Product with the highest average weekly sales is on index: 4
